"""add training_trainers (many-to-many) and training_recordings

Revision ID: b9d2f6a4c8e1
Revises: e7a1c3f9b2d4
Create Date: 2026-08-12 00:00:00.000000

Training moves from a single trainer_id column on training_programs to a many-to-many
training_trainers junction table (same shape as the existing training_trainees table),
so a training can have multiple Trainers.

Also adds training_recordings: a training can span several sessions over its life, and
each session may produce its own recording (hosted externally, e.g. SharePoint - this
just stores the link), so recordings are a growing list per training rather than a
single overwritable field - see app/hrms/services/training_service.py:add_recording/
list_recordings/delete_recording. Addable by HR/Admin or any of the training's
Trainers; deletable by whoever added it, or HR/Admin.

Data safety: every existing training_programs.trainer_id is copied into
training_trainers as its sole trainer BEFORE the column is dropped, so no training
loses its trainer, and every permission check that keys off "is this user one of the
training's trainers" behaves identically to the old single-trainer check for
pre-existing data (a set with exactly one member).

The trainer_id column carries a FK constraint - MySQL requires that be dropped
explicitly before DROP COLUMN (Postgres drops it implicitly) - looked up by inspecting
the live schema rather than assuming a specific constraint name, since autogenerated
names differ between databases bootstrapped via create_all() vs. a tracked migration
(same pattern as d4f8c2a6b9e1_widen_integer_fks_to_bigint.py).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b9d2f6a4c8e1'
down_revision: Union[str, None] = 'e7a1c3f9b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

BIGINT = sa.BigInteger().with_variant(sa.Integer(), 'sqlite')


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'training_trainers' not in existing_tables:
        op.create_table(
            'training_trainers',
            sa.Column('id', BIGINT, nullable=False),
            sa.Column('training_id', sa.BigInteger(), nullable=False),
            sa.Column('trainer_id', sa.BigInteger(), nullable=False),
            sa.ForeignKeyConstraint(['training_id'], ['training_programs.id'], ),
            sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('training_id', 'trainer_id', name='uq_training_trainer'),
        )

    if 'training_recordings' not in existing_tables:
        op.create_table(
            'training_recordings',
            sa.Column('id', BIGINT, nullable=False),
            sa.Column('training_id', sa.BigInteger(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=True),
            sa.Column('link_url', sa.String(length=2000), nullable=False),
            sa.Column('added_by', sa.BigInteger(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['training_id'], ['training_programs.id'], ),
            sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
        )

    inspector = sa.inspect(bind)
    existing_columns = {c["name"] for c in inspector.get_columns('training_programs')}

    if 'trainer_id' in existing_columns:
        training_programs = sa.table(
            'training_programs',
            sa.column('id', sa.BigInteger()),
            sa.column('trainer_id', sa.BigInteger()),
        )
        training_trainers = sa.table(
            'training_trainers',
            sa.column('training_id', sa.BigInteger()),
            sa.column('trainer_id', sa.BigInteger()),
        )
        # Backfill BEFORE dropping the column - one training_trainers row per existing
        # training, carrying forward its (only) trainer.
        rows = bind.execute(sa.select(training_programs.c.id, training_programs.c.trainer_id)).fetchall()
        if rows:
            op.bulk_insert(
                training_trainers,
                [{"training_id": r.id, "trainer_id": r.trainer_id} for r in rows],
            )

        for fk in inspector.get_foreign_keys('training_programs'):
            if fk['constrained_columns'] == ['trainer_id']:
                op.drop_constraint(fk['name'], 'training_programs', type_='foreignkey')
        op.drop_column('training_programs', 'trainer_id')


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {c["name"] for c in inspector.get_columns('training_programs')}

    if 'trainer_id' not in existing_columns:
        op.add_column('training_programs', sa.Column('trainer_id', sa.BigInteger(), nullable=True))
        op.create_foreign_key('fk_training_programs_trainer_id', 'training_programs', 'users', ['trainer_id'], ['id'])

        training_programs = sa.table(
            'training_programs',
            sa.column('id', sa.BigInteger()),
            sa.column('trainer_id', sa.BigInteger()),
        )
        training_trainers = sa.table(
            'training_trainers',
            sa.column('training_id', sa.BigInteger()),
            sa.column('trainer_id', sa.BigInteger()),
        )
        # Pick one trainer per training (the lowest id) to repopulate the dropped column.
        rows = bind.execute(
            sa.select(training_trainers.c.training_id, sa.func.min(training_trainers.c.trainer_id))
            .group_by(training_trainers.c.training_id)
        ).fetchall()
        for training_id, trainer_id in rows:
            bind.execute(
                training_programs.update()
                .where(training_programs.c.id == training_id)
                .values(trainer_id=trainer_id)
            )
        op.alter_column('training_programs', 'trainer_id', existing_type=sa.BigInteger(), nullable=False)

    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if 'training_recordings' in existing_tables:
        op.drop_table('training_recordings')
    if 'training_trainers' in existing_tables:
        op.drop_table('training_trainers')
