"""initial schema - mirrors existing KMS Java/JPA-managed MySQL schema

Revision ID: 0001
Revises:
Create Date: 2026-07-22

Hand-written (not autogenerated - no live DB was reachable in this environment) so that a
fresh dev/test database can be bootstrapped from scratch. Against the real production
database (which already has these tables, created by Hibernate's ddl-auto=update), run
`alembic stamp head` instead of `alembic upgrade head` so Alembic just records this as the
current baseline without trying to (re)create anything.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "mks_lms_roles",
        sa.Column("role_id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("role_name", sa.String(255), nullable=False, unique=True),
    )

    op.create_table(
        "mks_lms_user_type",
        sa.Column("user_type_id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_type_name", sa.String(255), nullable=False, unique=True),
    )

    op.create_table(
        "mks_kms_department",
        sa.Column("departmentId", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("departmentName", sa.String(255), nullable=False, unique=True),
        sa.Column("departmentDescription", sa.String(1000), nullable=True),
    )

    op.create_table(
        "mks_kms_account",
        sa.Column("accountId", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("accountName", sa.String(255), nullable=False, unique=True),
        sa.Column("accountDescription", sa.String(1000), nullable=True),
        sa.Column("departmentId", sa.Integer, nullable=True),
    )

    op.create_table(
        "mks_kms_category",
        sa.Column("categoryId", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("categoryName", sa.String(255), nullable=False, unique=True),
        sa.Column("categoryDescription", sa.String(1000), nullable=True),
        sa.Column("unrestrictedCategory", sa.Boolean, nullable=True),
    )

    op.create_table(
        "mks_kms_subcategory",
        sa.Column("subCategoryId", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("subCategoryName", sa.String(255), nullable=False, unique=True),
        sa.Column("subCategoryDescription", sa.String(1000), nullable=True),
    )

    op.create_table(
        "mks_kms_usermgmt",
        sa.Column("user_id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("user_name", sa.String(255), nullable=False),
        sa.Column("user_email", sa.String(255), nullable=False, unique=True),
        sa.Column("user_pwd", sa.String(255), nullable=False),
        sa.Column("user_created_ts", sa.DateTime, server_default=sa.func.now(), nullable=True),
        sa.Column("user_updated_ts", sa.DateTime, nullable=True),
        sa.Column("user_last_logged_in_ts", sa.DateTime, nullable=True),
        sa.Column("password_reset_required", sa.Boolean, nullable=True),
        sa.Column("password_reset_token", sa.String(255), nullable=True),
        sa.Column("token_created_time", sa.DateTime, nullable=True),
        sa.Column("profile_image_url", sa.String(2000), nullable=True),
        sa.Column("enabled", sa.Boolean, nullable=False, server_default=sa.false()),
    )

    op.create_table(
        "mks_lms_content",
        sa.Column("fileId", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column("fileName", sa.String(500), nullable=True),
        sa.Column("fileDescription", sa.String(1000), nullable=True),
        sa.Column("fileUrl", sa.String(2000), nullable=True),
        sa.Column("department", sa.Integer, nullable=True),
        sa.Column("account", sa.Integer, nullable=True),
        sa.Column("category", sa.Integer, nullable=True),
        sa.Column("subCategory", sa.Integer, nullable=True),
        sa.Column("createdTIMESTAMP", sa.DateTime, nullable=True),
        sa.Column("userType", sa.Integer, nullable=True),
    )

    op.create_table(
        "users_roles",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("mks_kms_usermgmt.user_id"), primary_key=True),
        sa.Column("role_id", sa.Integer, sa.ForeignKey("mks_lms_roles.role_id"), nullable=False),
    )

    op.create_table(
        "user_department",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("mks_kms_usermgmt.user_id"), primary_key=True),
        sa.Column("departmentId", sa.Integer, sa.ForeignKey("mks_kms_department.departmentId"), nullable=False),
    )

    op.create_table(
        "user_account",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("mks_kms_usermgmt.user_id"), primary_key=True),
        sa.Column("accountId", sa.Integer, sa.ForeignKey("mks_kms_account.accountId"), nullable=False),
    )

    op.create_table(
        "users_type",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("mks_kms_usermgmt.user_id"), primary_key=True),
        sa.Column("user_type_id", sa.Integer, sa.ForeignKey("mks_lms_user_type.user_type_id"), nullable=False),
    )


def downgrade() -> None:
    op.drop_table("users_type")
    op.drop_table("user_account")
    op.drop_table("user_department")
    op.drop_table("users_roles")
    op.drop_table("mks_lms_content")
    op.drop_table("mks_kms_usermgmt")
    op.drop_table("mks_kms_subcategory")
    op.drop_table("mks_kms_category")
    op.drop_table("mks_kms_account")
    op.drop_table("mks_kms_department")
    op.drop_table("mks_lms_user_type")
    op.drop_table("mks_lms_roles")
